// Copyright (c) 2026 GregOrigin. All Rights Reserved.

#if WITH_DEV_AUTOMATION_TESTS

#include "Misc/AutomationTest.h"
#include "FBlueLineSmartTagAnalyzer.h"
#include "UBlueLineTagCommentNode.h"
#include "Demos/UK2Node_KingSafety.h"
#include "Settings/UBlueLineEditorSettings.h"
#include "Modules/ModuleManager.h"
#include "EdGraph/EdGraph.h"
#include "EdGraphSchema_K2.h"
#include "GameplayTagContainer.h"
#include "Misc/ScopeExit.h"

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FBlueLineSmartTagsMetadataTest,
    "BlueLine.SmartTags.AutoTag.PersistsMetadata",
    EAutomationTestFlags::EditorContext | EAutomationTestFlags::ProductFilter)

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FBlueLineSmartTagsColorEditToggleTest,
    "BlueLine.SmartTags.AutoTag.RespectsBlueprintColorEditSetting",
    EAutomationTestFlags::EditorContext | EAutomationTestFlags::ProductFilter)

bool FBlueLineSmartTagsMetadataTest::RunTest(const FString& Parameters)
{
    FModuleManager::LoadModuleChecked<IModuleInterface>("BlueLineSmartTags");

    UBlueLineEditorSettings* Settings = GetMutableDefault<UBlueLineEditorSettings>();
    const bool bOriginalEnableBlueLine = Settings->bEnableBlueLine;
    const bool bOriginalEnableSmartTags = Settings->bEnableSmartTags;
    const bool bOriginalEnableAutoTagCommand = Settings->bEnableAutoTagCommand;
    const bool bOriginalAllowBlueprintColorEdits = Settings->bAllowBlueprintColorEdits;
    const int32 OriginalMinClusterSizeSelection = Settings->MinClusterSizeSelection;
    const float OriginalSemanticConfidenceThreshold = Settings->SemanticConfidenceThreshold;

    ON_SCOPE_EXIT
    {
        Settings->bEnableBlueLine = bOriginalEnableBlueLine;
        Settings->bEnableSmartTags = bOriginalEnableSmartTags;
        Settings->bEnableAutoTagCommand = bOriginalEnableAutoTagCommand;
        Settings->bAllowBlueprintColorEdits = bOriginalAllowBlueprintColorEdits;
        Settings->MinClusterSizeSelection = OriginalMinClusterSizeSelection;
        Settings->SemanticConfidenceThreshold = OriginalSemanticConfidenceThreshold;
    };

    Settings->bEnableBlueLine = true;
    Settings->bEnableSmartTags = true;
    Settings->bEnableAutoTagCommand = true;
    Settings->bAllowBlueprintColorEdits = true;
    Settings->MinClusterSizeSelection = 2;
    Settings->SemanticConfidenceThreshold = 1.0f;

    UEdGraph* TestGraph = NewObject<UEdGraph>();
    TestGraph->Schema = UEdGraphSchema_K2::StaticClass();

    UK2Node_KingSafety* NodeA = NewObject<UK2Node_KingSafety>(TestGraph);
    NodeA->NodePosX = 0;
    NodeA->NodePosY = 0;
    NodeA->AllocateDefaultPins();
    TestGraph->AddNode(NodeA, false, false);

    UK2Node_KingSafety* NodeB = NewObject<UK2Node_KingSafety>(TestGraph);
    NodeB->NodePosX = 320;
    NodeB->NodePosY = 0;
    NodeB->AllocateDefaultPins();
    TestGraph->AddNode(NodeB, false, false);

    FBlueLineSmartTagAnalyzer::AutoTagGraph(TestGraph, { NodeA, NodeB });

    TArray<UBlueLineTagCommentNode*> TagComments;
    for (UEdGraphNode* Node : TestGraph->Nodes)
    {
        if (UBlueLineTagCommentNode* TagComment = Cast<UBlueLineTagCommentNode>(Node))
        {
            TagComments.Add(TagComment);
        }
    }

    TestEqual(TEXT("Auto-tagging should create exactly one semantic comment node"), TagComments.Num(), 1);
    if (TagComments.Num() != 1)
    {
        return false;
    }

    const FGameplayTag ExpectedCombatTag = FGameplayTag::RequestGameplayTag(FName("BlueLine.Type.Combat"), false);
    TestTrue(TEXT("Generated comment should be marked as auto-generated"), TagComments[0]->bBlueLineAutoGenerated);
    TestTrue(TEXT("Generated comment should persist a valid semantic tag"), TagComments[0]->BlueLineSemanticTag.IsValid());
    TestEqual(TEXT("Generated comment should persist the strongest semantic tag"), TagComments[0]->BlueLineSemanticTag, ExpectedCombatTag);

    return true;
}

bool FBlueLineSmartTagsColorEditToggleTest::RunTest(const FString& Parameters)
{
    FModuleManager::LoadModuleChecked<IModuleInterface>("BlueLineSmartTags");

    UBlueLineEditorSettings* Settings = GetMutableDefault<UBlueLineEditorSettings>();
    const bool bOriginalEnableBlueLine = Settings->bEnableBlueLine;
    const bool bOriginalEnableSmartTags = Settings->bEnableSmartTags;
    const bool bOriginalEnableAutoTagCommand = Settings->bEnableAutoTagCommand;
    const bool bOriginalAllowBlueprintColorEdits = Settings->bAllowBlueprintColorEdits;
    const int32 OriginalMinClusterSizeSelection = Settings->MinClusterSizeSelection;
    const float OriginalSemanticConfidenceThreshold = Settings->SemanticConfidenceThreshold;

    ON_SCOPE_EXIT
    {
        Settings->bEnableBlueLine = bOriginalEnableBlueLine;
        Settings->bEnableSmartTags = bOriginalEnableSmartTags;
        Settings->bEnableAutoTagCommand = bOriginalEnableAutoTagCommand;
        Settings->bAllowBlueprintColorEdits = bOriginalAllowBlueprintColorEdits;
        Settings->MinClusterSizeSelection = OriginalMinClusterSizeSelection;
        Settings->SemanticConfidenceThreshold = OriginalSemanticConfidenceThreshold;
    };

    Settings->bEnableBlueLine = true;
    Settings->bEnableSmartTags = true;
    Settings->bEnableAutoTagCommand = true;
    Settings->bAllowBlueprintColorEdits = false;
    Settings->MinClusterSizeSelection = 2;
    Settings->SemanticConfidenceThreshold = 1.0f;

    UEdGraph* TestGraph = NewObject<UEdGraph>();
    TestGraph->Schema = UEdGraphSchema_K2::StaticClass();

    UBlueLineTagCommentNode* BaselineCommentNode = NewObject<UBlueLineTagCommentNode>(TestGraph);
    BaselineCommentNode->PostPlacedNewNode();
    const FLinearColor DefaultCommentColor = BaselineCommentNode->CommentColor;

    UK2Node_KingSafety* NodeA = NewObject<UK2Node_KingSafety>(TestGraph);
    NodeA->NodePosX = 0;
    NodeA->NodePosY = 0;
    NodeA->AllocateDefaultPins();
    TestGraph->AddNode(NodeA, false, false);

    UK2Node_KingSafety* NodeB = NewObject<UK2Node_KingSafety>(TestGraph);
    NodeB->NodePosX = 320;
    NodeB->NodePosY = 0;
    NodeB->AllocateDefaultPins();
    TestGraph->AddNode(NodeB, false, false);

    FBlueLineSmartTagAnalyzer::AutoTagGraph(TestGraph, { NodeA, NodeB });

    TArray<UBlueLineTagCommentNode*> TagComments;
    for (UEdGraphNode* Node : TestGraph->Nodes)
    {
        if (UBlueLineTagCommentNode* TagComment = Cast<UBlueLineTagCommentNode>(Node))
        {
            TagComments.Add(TagComment);
        }
    }

    TestEqual(TEXT("Auto-tagging should still create a semantic comment node when color edits are disabled"), TagComments.Num(), 1);
    if (TagComments.Num() != 1)
    {
        return false;
    }

    TestTrue(
        TEXT("Disabling Blueprint color edits should preserve the default comment color"),
        TagComments[0]->CommentColor.Equals(DefaultCommentColor, KINDA_SMALL_NUMBER));

    return true;
}

#endif // WITH_DEV_AUTOMATION_TESTS
