// Copyright (c) 2026 GregOrigin. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "EdGraphNode_Comment.h"
#include "GameplayTagContainer.h"

#include "UBlueLineTagCommentNode.generated.h"

/**
 * Comment node that persists BlueLine semantic tag metadata alongside the visual comment box.
 */
UCLASS()
class BLUELINESMARTTAGS_API UBlueLineTagCommentNode : public UEdGraphNode_Comment
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, Category = "BlueLine")
	FGameplayTag BlueLineSemanticTag;

	UPROPERTY(EditAnywhere, Category = "BlueLine")
	bool bBlueLineAutoGenerated = true;
};
